---
title: "Week 4 - SQL and DuckDB"
---

## Learning objectives

Continued exploration of SQL concepts, including:

- nesting SQL queries
- different type of joins



## Monday Session

Let's open our ASDN database:

```bash
duckdb database.duckdb
```

Let's check we are in the right database

```
D .table
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ     Bird_nests     в”Ӯв”Ӯ     Bird_eggs     в”Ӯв”Ӯ       Site        в”Ӯв”Ӯ Camp_assignment  в”Ӯв”Ӯ         Species         в”Ӯ
в”Ӯ                    в”Ӯв”Ӯ                   в”Ӯв”Ӯ                   в”Ӯв”Ӯ                  в”Ӯв”Ӯ                         в”Ӯ
в”Ӯ Book_page  varchar в”Ӯв”Ӯ Book_page varchar в”Ӯв”Ӯ Code      varchar в”Ӯв”Ӯ Year     integer в”Ӯв”Ӯ Code            varchar в”Ӯ
в”Ӯ Year       integer в”Ӯв”Ӯ Year      integer в”Ӯв”Ӯ Site_name varchar в”Ӯв”Ӯ Site     varchar в”Ӯв”Ӯ Common_name     varchar в”Ӯ
в”Ӯ Site       varchar в”Ӯв”Ӯ Site      varchar в”Ӯв”Ӯ Location  varchar в”Ӯв”Ӯ Observer varchar в”Ӯв”Ӯ Scientific_name varchar в”Ӯ
в”Ӯ Nest_ID    varchar в”Ӯв”Ӯ Nest_ID   varchar в”Ӯв”Ӯ Latitude  float   в”Ӯв”Ӯ Start    date    в”Ӯв”Ӯ Relevance       varchar в”Ӯ
в”Ӯ Species    varchar в”Ӯв”Ӯ Egg_num   integer в”Ӯв”Ӯ Longitude float   в”Ӯв”Ӯ End      date    в”Ӯв”Ӯ                         в”Ӯ
в”Ӯ Observer   varchar в”Ӯв”Ӯ Length    float   в”Ӯв”Ӯ Area      float   в”Ӯв”Ӯ                  в”Ӯв”Ӯ         99 rows         в”Ӯ
в”Ӯ Date_found date    в”Ӯв”Ӯ Width     float   в”Ӯв”Ӯ                   в”Ӯв”Ӯ     441 rows     в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
в”Ӯ how_found  varchar в”Ӯв”Ӯ                   в”Ӯв”Ӯ      16 rows      в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
в”Ӯ Clutch_max integer в”Ӯв”Ӯ     406 rows      в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ                    
в”Ӯ floatAge   float   в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ                                         
в”Ӯ ageMethod  varchar в”Ӯ                                                              
в”Ӯ                    в”Ӯ                                                              
в”Ӯ     1547 rows      в”Ӯ                                                              
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ                                                              
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ      Personnel       в”Ӯ
в”Ӯ                      в”Ӯ
в”Ӯ Abbreviation varchar в”Ӯ
в”Ӯ Name         varchar в”Ӯ
в”Ӯ                      в”Ӯ
в”Ӯ       269 rows       в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```


### Tri-value logic

- Expressions can return TRUE, FALSE, or NULL
- NULL is infectious
- In filtering, only TRUE counts

```sql
SELECT COUNT(*) FROM Bird_nests
  WHERE floatAge < 7 OR floatAge >= 7;
```

Only returns a fraction of the rows due to floatAge being NULL

In SQL, if you want to ask (or not ask) for NULLs: `IS NULL`, or `IS NOT NULL`


### Nesting queries for more complex analysis

- Everything returned by an SQL query is a table
- Even SELECT COUNT(*) returns a table
- Wherever a table is requested, you can insert a parenthesized query; similarly to the tidyverse piping


#### What species are *not* represented in the Bird_nests table?

```sql
SELECT * FROM Species WHERE
  Code NOT IN (SELECT DISTINCT Species FROM Bird_nests);
```

#### Which site are located in Canada and have an area larger than 200?

```sql
SELECT Location, MAX(Area) AS Max_area
  FROM Site
  WHERE Location LIKE '%Canada'
  GROUP BY Location
  HAVING Max_area > 200;
```

**Note: `HAVING` is used to filter data on condition in combination of `GROUP BY`, whereas `WHERE` is used to filter rows.**

Now let's imagine there was no `HAVING` clause. How would you answer the above question?

```sql
SELECT Location, Max_area FROM
    (SELECT Location, MAX(Area) AS Max_area
      FROM Site
      WHERE Location LIKE '%Canada'
      GROUP BY Location)
  WHERE Max_area > 200;
```


### Joins

**For this part, we are using the `toy.duckdb`**. Make sure you sync your fork and pull the latest version of our
data repository.

```bash
duckdb toy.duckdb
```

```
D .table
```

```output
 в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ toy в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ 
 в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ main в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ 
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ      Student       в”Ӯв”Ӯ       House        в”Ӯв”Ӯ       B       в”Ӯв”Ӯ       A       в”Ӯ
в”Ӯ                    в”Ӯв”Ӯ                    в”Ӯв”Ӯ               в”Ӯв”Ӯ               в”Ӯ
в”Ӯ Student_ID integer в”Ӯв”Ӯ House_ID   integer в”Ӯв”Ӯ bcol1 integer в”Ӯв”Ӯ acol1 integer в”Ӯ
в”Ӯ Name       varchar в”Ӯв”Ӯ Name       varchar в”Ӯв”Ӯ bcol2 varchar в”Ӯв”Ӯ acol2 varchar в”Ӯ
в”Ӯ Birthdate  date    в”Ӯв”Ӯ Headmaster varchar в”Ӯв”Ӯ bcol3 varchar в”Ӯв”Ӯ               в”Ӯ
в”Ӯ House_ID   integer в”Ӯв”Ӯ                    в”Ӯв”Ӯ               в”Ӯв”Ӯ    3 rows     в”Ӯ
в”Ӯ                    в”Ӯв”Ӯ       3 rows       в”Ӯв”Ӯ    3 rows     в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
в”Ӯ       4 rows       в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ                                       
```

#### Cartesian product 

- Conceptually, the database performs a Cartesian product of the
  tables and then applies the join condition to filter
- In some databases, can do a Cartesian product saying JOIN
  with no join condition
- But in DuckDB, need to use `CROSS JOIN`


Let's have a look at out tables

```sql
SELECT * FROM A;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ acol1 в”Ӯ   acol2   в”Ӯ
в”Ӯ int32 в”Ӯ  varchar  в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ     1 в”Ӯ apple     в”Ӯ
в”Ӯ     2 в”Ӯ banana    в”Ӯ
в”Ӯ     3 в”Ӯ cranberry в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

```sql
SELECT * FROM B;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ bcol1 в”Ӯ  bcol2  в”Ӯ  bcol3   в”Ӯ
в”Ӯ int32 в”Ӯ varchar в”Ӯ varchar  в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ     1 в”Ӯ pie     в”Ӯ streusel в”Ӯ
в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

```sql
SELECT * FROM A CROSS JOIN B;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ acol1 в”Ӯ   acol2   в”Ӯ bcol1 в”Ӯ  bcol2  в”Ӯ  bcol3   в”Ӯ
в”Ӯ int32 в”Ӯ  varchar  в”Ӯ int32 в”Ӯ varchar в”Ӯ varchar  в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ     1 в”Ӯ apple     в”Ӯ     1 в”Ӯ pie     в”Ӯ streusel в”Ӯ
в”Ӯ     1 в”Ӯ apple     в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     1 в”Ӯ apple     в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ     2 в”Ӯ banana    в”Ӯ     1 в”Ӯ pie     в”Ӯ streusel в”Ӯ
в”Ӯ     2 в”Ӯ banana    в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     2 в”Ӯ banana    в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ     3 в”Ӯ cranberry в”Ӯ     1 в”Ӯ pie     в”Ӯ streusel в”Ӯ
в”Ӯ     3 в”Ӯ cranberry в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     3 в”Ӯ cranberry в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

As a result of a cross-join between to table you have a table that has the following characteristics:

- Number of rows: **product of number of rows** from tables A & B
- Number of columns:  **sum of number of columns** from tables A & B 


#### Cross-joins with a condition

When there is a condition added, `JOIN` defaults to **inner join**

```sql
SELECT * FROM A JOIN B ON acol1 < bcol1;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ acol1 в”Ӯ  acol2  в”Ӯ bcol1 в”Ӯ  bcol2  в”Ӯ  bcol3   в”Ӯ
в”Ӯ int32 в”Ӯ varchar в”Ӯ int32 в”Ӯ varchar в”Ӯ varchar  в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ     1 в”Ӯ apple   в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     1 в”Ӯ apple   в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ     2 в”Ӯ banana  в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

- Left or right outer join: selects rows not included, supplies NULL for values
  in other table

```sql
SELECT * FROM A RIGHT JOIN B ON acol1 < bcol1;
```

```output
в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ acol1 в”Ӯ  acol2  в”Ӯ bcol1 в”Ӯ  bcol2  в”Ӯ  bcol3   в”Ӯ
в”Ӯ int32 в”Ӯ varchar в”Ӯ int32 в”Ӯ varchar в”Ӯ varchar  в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ     1 в”Ӯ apple   в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     1 в”Ӯ apple   в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ     2 в”Ӯ banana  в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ  NULL в”Ӯ NULL    в”Ӯ     1 в”Ӯ pie     в”Ӯ streusel в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

- Notice how get B's row 1 now (because B is the "right table")
- Similar for left side

```sql
SELECT * FROM A LEFT JOIN B ON acol1 < bcol1;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ acol1 в”Ӯ   acol2   в”Ӯ bcol1 в”Ӯ  bcol2  в”Ӯ  bcol3   в”Ӯ
в”Ӯ int32 в”Ӯ  varchar  в”Ӯ int32 в”Ӯ varchar в”Ӯ varchar  в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ     1 в”Ӯ apple     в”Ӯ     2 в”Ӯ cake    в”Ӯ frosting в”Ӯ
в”Ӯ     1 в”Ӯ apple     в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ     2 в”Ӯ banana    в”Ӯ     3 в”Ӯ cookie  в”Ӯ NULL     в”Ӯ
в”Ӯ     3 в”Ӯ cranberry в”Ӯ  NULL в”Ӯ NULL    в”Ӯ NULL     в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

- Now we we have the missing row from the A (left) table

- Do a FULL OUTER JOIN to get both missing sides (rare)


#### Relational join

- In the case of a join on a foreign key, the effect is to add columns to
  the "many" table
  
```sql
SELECT * FROM House;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ House_ID в”Ӯ    Name    в”Ӯ     Headmaster     в”Ӯ
в”Ӯ  int32   в”Ӯ  varchar   в”Ӯ      varchar       в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в”Ӯ        2 в”Ӯ Hufflepuff в”Ӯ Pomona Sprout      в”Ӯ
в”Ӯ        3 в”Ӯ Slytherin  в”Ӯ Severus Snape      в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

```sql
SELECT * FROM Student;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ Student_ID в”Ӯ       Name       в”Ӯ Birthdate  в”Ӯ House_ID в”Ӯ
в”Ӯ   int32    в”Ӯ     varchar      в”Ӯ    date    в”Ӯ  int32   в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ          1 в”Ӯ Harry Potter     в”Ӯ 1980-07-31 в”Ӯ        1 в”Ӯ
в”Ӯ          2 в”Ӯ Hermione Granger в”Ӯ 1979-09-19 в”Ӯ        1 в”Ӯ
в”Ӯ          3 в”Ӯ Draco Malfoy     в”Ӯ 1980-06-05 в”Ӯ        3 в”Ӯ
в”Ӯ          4 в”Ӯ Ginny Weasley    в”Ӯ 1981-08-11 в”Ӯ        1 в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

```
D .schema
```

```sql
SELECT * FROM Student AS S JOIN House AS H ON S.House_ID = H.House_ID;
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ Student_ID в”Ӯ       Name       в”Ӯ Birthdate  в”Ӯ House_ID в”Ӯ House_ID в”Ӯ    Name    в”Ӯ     Headmaster     в”Ӯ
в”Ӯ   int32    в”Ӯ     varchar      в”Ӯ    date    в”Ӯ  int32   в”Ӯ  int32   в”Ӯ  varchar   в”Ӯ      varchar       в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ          1 в”Ӯ Harry Potter     в”Ӯ 1980-07-31 в”Ӯ        1 в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в”Ӯ          2 в”Ӯ Hermione Granger в”Ӯ 1979-09-19 в”Ӯ        1 в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в”Ӯ          3 в”Ӯ Draco Malfoy     в”Ӯ 1980-06-05 в”Ӯ        3 в”Ӯ        3 в”Ӯ Slytherin  в”Ӯ Severus Snape      в”Ӯ
в”Ӯ          4 в”Ӯ Ginny Weasley    в”Ӯ 1981-08-11 в”Ӯ        1 в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```


- more compact syntax, since the columns used to join have the same name in each table:

```sql
SELECT * FROM Student JOIN House USING (House_ID);
```

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ Student_ID в”Ӯ       Name       в”Ӯ Birthdate  в”Ӯ House_ID в”Ӯ    Name    в”Ӯ     Headmaster     в”Ӯ
в”Ӯ   int32    в”Ӯ     varchar      в”Ӯ    date    в”Ӯ  int32   в”Ӯ  varchar   в”Ӯ      varchar       в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ          1 в”Ӯ Harry Potter     в”Ӯ 1980-07-31 в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в”Ӯ          2 в”Ӯ Hermione Granger в”Ӯ 1979-09-19 в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в”Ӯ          3 в”Ӯ Draco Malfoy     в”Ӯ 1980-06-05 в”Ӯ        3 в”Ӯ Slytherin  в”Ӯ Severus Snape      в”Ӯ
в”Ӯ          4 в”Ӯ Ginny Weasley    в”Ӯ 1981-08-11 в”Ӯ        1 в”Ӯ Gryffindor в”Ӯ Minerva McGonagall в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```

Note that the `USING` clause also keep only **one** of key columns!


#### Let's switch back to our ASDN database

```bash
duckdb database.duckdb
```

```
D .mode line
```

:::  callout-tip
## DuckDB Modes

DuckDB's different output formats: <https://duckdb.org/docs/current/clients/cli/output_formats>
:::

Let's have a look at the `Bird_eggs` and `Bird_nests` tables:
```sql
SELECT COUNT(*) FROM Bird_eggs;
SELECT * FROM Bird_eggs LIMIT 1;
SELECT * FROM Bird_nests LIMIT 1;
```

We can use Nest_ID to join those two tables

```sql
SELECT * FROM Bird_eggs
  JOIN Bird_nests USING (Nest_ID)
  LIMIT 1;
```

Let's also join the Species table to bring more readable names:

```sql
SELECT * FROM Bird_eggs
  JOIN Bird_nests USING (Nest_ID)
  JOIN Species ON Species = Code
  LIMIT 1;
```

#### When to order rows when joining tables?

**Ordering is assuredly lost in a join.**  An entirely new table is formed.

This is pointless:

```sql
SELECT * FROM
  (SELECT * FROM Bird_eggs ORDER BY Width)
  JOIN Bird_nests
  USING (Nest_ID);
```

#### GOTCHA WITH GROUPING

DuckDB not smart enough to recognize primary keys uniqueness rule in joins

```sql
SELECT Nest_ID, COUNT(*)
  FROM Bird_nests JOIN Bird_eggs USING (Nest_ID)
  GR`OUP BY Nest_ID;
```

- Can we add another column from Bird_nests?  Other RDBMs's say yes
- DuckDB: no
- So follow DuckDB's suggestions

```sql
SELECT Nest_ID, ANY_VALUE(Species), COUNT(*)
  FROM Bird_nests JOIN Bird_eggs USING (Nest_ID)
  GROUP BY Nest_ID;
 ```
 
 ```sql
SELECT Nest_ID, Species, COUNT(*)
  FROM Bird_nests JOIN Bird_eggs USING (Nest_ID)
  GROUP BY Nest_ID, Species;
```

## Wednesday session

::: callout-warning  
##POSIT WORKBENCH

- Beware of the lock with active sessions!!
- Always quit DuckDB before leaving workbench

If you can not find the session, you can kill the process running it on the server. In the DuckDB error message,  the PID of that process owning the lock will be provided. You can use it to kill this process and remove the lock:

```bash
kill PID
```
:::

### Add a new table

As we mentioned, you can use SQL to add a new table to your database. Now that we have cleaned our snow data we might want to add this table to our database.

```sql
CREATE TABLE Snow_cover (
    Site VARCHAR NOT NULL,
    Year INTEGER NOT NULL CHECK (Year BETWEEN 1990 AND 2018),
    Date DATE NOT NULL,
    Plot VARCHAR NOT NULL,
    Location VARCHAR NOT NULL,
    Snow_cover REAL CHECK (Snow_cover BETWEEN 0 AND 130),
    Water_cover REAL CHECK (Water_cover BETWEEN 0 AND 130),
    Land_cover REAL CHECK (Land_cover BETWEEN 0 AND 130),
    Total_cover REAL CHECK (Total_cover BETWEEN 0 AND 130),
    Observer VARCHAR,
    Notes VARCHAR,
    PRIMARY KEY (Site, Plot, Location, Date),
    FOREIGN KEY (Site) REFERENCES Site (Code)
);
```

Let's check if the table was added to our database:

```
D .table
```

Our table should have no data in it:

```sql
SELECT * FROM Snow_cover LIMIT 5;
```

Now we can import the data from our csv file into our database:

```sql
COPY Snow_cover FROM "../ASDN_csv/snow_survey_fixed.csv" (header TRUE, nullstr "NA");
```

Let's check:

```sql
SELECT * FROM Snow_cover LIMIT 5;
```

рҹҺү import successful!!

::: callout-note
## Challenge

- Ask 1: What is the average snow cover at each site?

- Ask2: Top 5 most snowy sites

:::

### Temporary table

Since every query output is a table, we can save any query as new table!

We can for example create a backup of an entire table:

```sql
CREATE TEMP TABLE Camp_assignment_copy AS
   SELECT * FROM Camp_assignment; 
```

Let's check things:

```
D .table
```

Of course it can be a more complex query. Let's say we often need to know which person worked at a specific site, We could use this query:

```sql
SELECT Year, Site, Name 
   FROM Camp_assignment_copy JOIN Personnel ON Observer = Abbreviation;
```

Since we need this query often we might want to save it... and since each SQL quey table returns a table, we can simply save it as a new table:

```sql
CREATE TEMP TABLE Camp_personnel_tmp AS
   SELECT Year, Site, Name 
   FROM Camp_assignment_copy JOIN Personnel ON Observer = Abbreviation;
```

Let's check things:

```
D .table
```

Note that it does not have to be a JOIN, it can be any operations such as filetering the rows with a `WHERE` clause!

What is special about a TEMP TABLE vs a TABLE? It is deleted when you exit the database. In other words, temporary tables are only available to the  current session. 

However a **TEMP TABLE is materialized and thus static**.

But wait there is even better...


### Views

- a view looks like a table
- virtual, **not** materialized like CREATE TABLE AS
- virtual implies always reflects current data in source tables, i.e.,
  view is (re-)executed each time it is referenced
- can make normalized tables more palatable; reduce the number of joins
  one has to do manually


```sql
CREATE VIEW Camp_personnel_v AS
   SELECT Year, Site, Name 
   FROM Camp_assignment_copy JOIN Personnel ON Observer = Abbreviation;
```

A VIEW is also stored in the database!

```
D .table
```

Also try:

```
D .schema
```

::: Callout-tips
Note that the VIEWs are mixed with the regular TABLEs. Why do you think?

How to list all the views in DuckDB: 

```sql
SELECT view_name FROM duckdb_views;
```
:::

#### Stressing the differences between a VIEW and a (TMP) TABLE:

**DANGER ZONE**

Let's say the site `bylo` has been remove from our study. We thus want to delete those rows. Since it is a destructive action, it is a good idea to first run the query as a SELECT then switch to the DELETE


```sql 
SELECT * FROM Camp_assignment_copy WHERE Site == 'bylo';
```

OK, we are ready to delete:

```sql 
DELETE FROM Camp_assignment_copy WHERE Site == 'bylo';
```

Let's check:

Did the temporary table update?
```sql 
SELECT * FROM Camp_personnel_tmp LIMIT 10;
```

Did the view update?
```sql 
SELECT * FROM Camp_personnel_v LIMIT 10;
```


### Dropping things

You can also use `DROP` to delete a table, temp table, view, ... and more:

```sql 
DROP TABLE Camp_personnel_tmp;
```

Note the lack of TEMP when dropping a temporary table!

```sql 
DROP VIEW Camp_personnel_v;
```

::: callout-note
## Challenge

- Close the database
- Reopen the database

What tables do you see?
:::



### SET OPERATIONS

- UNION, INTERSECT, EXCEPT
- last one is set difference

### 3rd way to get species that do *not* have nest data: use EXCEPT

- First way:
```sql
SELECT Code FROM Species WHERE Code NOT IN (SELECT DISTINCT Species FROM Bird_nests);
```

- Second way:
```sql
SELECT BN.Species, S.Code FROM Bird_nests BN RIGHT JOIN Species S ON BN.Species = S.Code WHERE BN.Species IS NULL;
```

- Third way
```sql
SELECT Code FROM Species
  EXCEPT
  SELECT DISTINCT Species FROM Bird_nests;
```

- example of UNION: suppose book b14 measured in inches,
  not millimeters, let's adjust on fly
```sql
  SELECT Book_page, Nest_ID, Egg_num, Length*25.4, Width*25.4
      FROM Bird_eggs
      WHERE Book_page LIKE 'b14%'
  UNION
  SELECT Book_page, Nest_ID, Egg_num, Length, Width
      FROM Bird_eggs
      WHERE Book_page NOT LIKE 'b14%';
```

- ^^ what if Book_page is NULL?
- caution: not really looking at names of columns, just #columns and data types
- so is possible to union nonsensical things together
- UNION throws out duplicates, UNION ALL keeps all

Perhaps better example of UNION: let's create a table of all
bird nests and egg counts, including nests that have no egg data recorded.

```sql
SELECT Nest_ID, COUNT(*) AS Num_eggs
  FROM Bird_eggs
  GROUP BY Nest_ID

UNION

SELECT Nest_ID, 0 AS Num_eggs
  FROM Bird_nests
  WHERE Nest_ID NOT IN (SELECT DISTINCT Nest_ID FROM Bird_eggs);
```  


## Resources

Lecture notes:

-   [lecture-notes-04-mon.txt](lecture-notes-04-mon.txt)
-   [in-class-script-04-mon.sql](in-class-script-04-mon.sql)
-   [lecture-notes-04-wed.txt](lecture-notes-04-wed.txt)
-   [lecture-notes-data-management-io.sql](lecture-notes-data-management-io.txt)


Data:

- [Class data GitHub repository](https://github.com/UCSB-Library-Research-Data-Services/bren-eds213-data)



