---
title: "Week 8.2 - How walkable is my favorite location in the US?"
format: html
---

**Upload you SQL script named `mywalkability_yourfullname` with your answer to the questions to Canvas: <https://ucsb.instructure.com/courses/32934/assignments/477543>**

In this assignment, you will investigate the walkability of a chosen location in the United States and compare its score against regional averages. Your final submission will be a DuckDB SQL script uploaded to Canvas that executes the following steps:

- Initialize a new DuckDB database.
- Import State and County names from the `fips_state_county.csv`, saving it as a table named `Fips`.
- Load the Walkability Index data for your selected state from `walkability_wgs84.parquet` into a table named `Walkability_mystate` (for example, `Walkability_ca` for California).
- Identify the specific Walkability Index value for your location's US Census Group Block.
- Conduct a comparison between this value and the average scores for its respective Census Tract and County.
- Export the resulting table to a csv file format.

To do so, we will need to use two extensions from DuckDB `spatial` and `httpfs`:

```sql
-- INSTALL spatial;
LOAD spatial;
-- INSTALL httpfs;
LOAD httpfs;
```

## Choosing you location

1. Select a US-based location to research, such as your hometown or a favorite destination.
2. Determine the latitude and longitude coordinates for your chosen site using Google Maps or a similar tool.
3. Include these geographic details (name, lat, long, ...) as a comment within your SQL script.


## Data import (15pts)

There are two files we need to import:

- Create at table named `Fips` from the State and County Name: `fips_state_county.csv` (5pts)
- Create a table named `Walkability_mystate` (e.g. `Walkability_ca` for California) from the Walkability national database in WGS84 projection: `walkability_wgs84.parquet`  by selecting the following columns: `GEOID10, STATEFP, COUNTYFP, TRACTCE, BLKGRPCE, CBSA, CBSA_Name, TotPop, NatWalkInd, geom_wgs84` and adding a WHERE close for your state (10pts)

Good news, those files are ready on Workbench! You can import them using the following URL + the filename you want to import: `https://apps.bren.ucsb.edu/eds213-data/walkability/`

**Hint**: Look at the DuckDB documentation (<https://duckdb.org/docs/current/data/overview>) for `read_csv` and `read_parquet`.

Your schema should look like this:

```output
в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ main в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ 
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ          Walkability_ca          в”Ӯв”Ӯ        Fips         в”Ӯ
в”Ӯ                                  в”Ӯв”Ӯ                     в”Ӯ
в”Ӯ GEOID10    varchar               в”Ӯв”Ӯ STATEFP     varchar в”Ӯ
в”Ӯ STATEFP    varchar               в”Ӯв”Ӯ State_name  varchar в”Ӯ
в”Ӯ COUNTYFP   varchar               в”Ӯв”Ӯ COUNTYFP    varchar в”Ӯ
в”Ӯ TRACTCE    varchar               в”Ӯв”Ӯ County_name varchar в”Ӯ
в”Ӯ BLKGRPCE   varchar               в”Ӯв”Ӯ                     в”Ӯ
в”Ӯ CBSA       varchar               в”Ӯв”Ӯ      3154 rows      в”Ӯ
в”Ӯ CBSA_Name  varchar               в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
в”Ӯ TotPop     integer               в”Ӯ
в”Ӯ NatWalkInd double                в”Ӯ
в”Ӯ geom_wgs84 geometry('ogc:crs84') в”Ӯ
в”Ӯ                                  в”Ӯ
в”Ӯ            23212 rows            в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```


## Join Tables (10pts)
 
Join the two tables and store the results in a VIEW named `Walkind_mystate`
 
Our schema should like something like this:

```output
 в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ main в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ 
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ          Walkability_ca          в”Ӯв”Ӯ            Walkind_ca             в”Ӯв”Ӯ        Fips         в”Ӯ
в”Ӯ                                  в”Ӯв”Ӯ                                   в”Ӯв”Ӯ                     в”Ӯ
в”Ӯ GEOID10    varchar               в”Ӯв”Ӯ GEOID10     varchar               в”Ӯв”Ӯ STATEFP     varchar в”Ӯ
в”Ӯ STATEFP    varchar               в”Ӯв”Ӯ STATEFP     varchar               в”Ӯв”Ӯ State_name  varchar в”Ӯ
в”Ӯ COUNTYFP   varchar               в”Ӯв”Ӯ COUNTYFP    varchar               в”Ӯв”Ӯ COUNTYFP    varchar в”Ӯ
в”Ӯ TRACTCE    varchar               в”Ӯв”Ӯ TRACTCE     varchar               в”Ӯв”Ӯ County_name varchar в”Ӯ
в”Ӯ BLKGRPCE   varchar               в”Ӯв”Ӯ BLKGRPCE    varchar               в”Ӯв”Ӯ                     в”Ӯ
в”Ӯ CBSA       varchar               в”Ӯв”Ӯ CBSA        varchar               в”Ӯв”Ӯ      3154 rows      в”Ӯ
в”Ӯ CBSA_Name  varchar               в”Ӯв”Ӯ CBSA_Name   varchar               в”Ӯв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
в”Ӯ TotPop     integer               в”Ӯв”Ӯ TotPop      integer               в”Ӯ
в”Ӯ NatWalkInd double                в”Ӯв”Ӯ NatWalkInd  double                в”Ӯ
в”Ӯ geom_wgs84 geometry('ogc:crs84') в”Ӯв”Ӯ geom_wgs84  geometry('ogc:crs84') в”Ӯ
в”Ӯ                                  в”Ӯв”Ӯ State_name  varchar               в”Ӯ
в”Ӯ            23212 rows            в”Ӯв”Ӯ County_name varchar               в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```
 
## Walkability index at your location (15pts)
 
You are now ready to execute your initial spatial query! Your objective is to identify the US Census  Group Block containing your chosen point of interest, following the methodology we practiced in class.

Determine the walkability index for your location. In your script, include a comment that evaluates this value against the walkability index scale and note whether the findings align with your expectations.

**Hint**: Keep in mind that the latitude and longitude sequence in Google Maps may differ from that required by the `ST_Point` function.


## Average Walkability index at your Census Tract (10pts)

Now, compute the average Walkability index at the Census tract level and the number of Group Block within this Tract, getting your Tract ID from the previous query.

**Hint**: A Tract ID is only unique within one specific County and the County FIPS is only unique within a specific State!!

Your results should look like this: 

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ TRACTCE в”Ӯ Block_count в”Ӯ Walkind_tract_avg в”Ӯ
в”Ӯ varchar в”Ӯ    int64    в”Ӯ      double       в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ 000400  в”Ӯ           5 в”Ӯ              11.7 в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```


## Average Walkability index at your County Level (10pts)

Now, compute the average Walkability index at the County level and the total number of Group Blocks in that County. Get the necessary information from previous queries.

```output
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ COUNTYFP в”Ӯ  County_name  в”Ӯ Block_count в”Ӯ Walkind_county_avg в”Ӯ
в”Ӯ varchar  в”Ӯ    varchar    в”Ӯ    int64    в”Ӯ       double       в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ 083      в”Ӯ SANTA BARBARA в”Ӯ         313 в”Ӯ 10.495740149094784 в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
```


## Discuss your results (5pts)

Add a comment in your SQL script to discuss how your favorite location's walkability index compares to its surrounding. From your knowledge about the area, does that make sense?


## Export your results (20pts)

It is time to export your results! We want a table with (15pts):

- Only Observations for the Tract of your location of interest
- Add the average Tract walkability as a column (same value repeating)
- Add the average County walkability as a column (same value repeating)

Save it as a csv file. Inspect this csv file, was the geometry column saved? Comment in your script (5pts).

No need to submit your csv file


**Credit: 85 points**

