---
title: "Week 8 - DB advanced topics & Ethical and Responsible Data Management"
---

## Learning objectives

- Understand core ethical and responsible data management principles, particularly those related to self-governance, conflict management, mitigating bias and harm, and appropriately handling sensitive data.

- Articulate these principles in the context of real-world scenarios relevant to environmental sciences research.


## Slides

[slides-08.pdf](slides-08.pdf)

*Suggested readings*

1.  Boté, J. J., & Térmens, M. (2019). Reusing data: Technical and ethical challenges. DESIDOC Journal of Library & Information Technology, 39(6) <http://hdl.handle.net/2445/151341>

2.  McGovern, A., Ebert-Uphoff, I., Gagne, D., & Bostrom, A. (2022). Why we need to focus on developing ethical, responsible, and trustworthy artificial intelligence approaches for environmental science. Environmental Data Science, 1, E6. <https://doi.org/10.1017/eds.2022.5>

*Additional suggested readings are noted in the slides.*

## Case-based discussion:

-   Case Study A: [Containing the flames of bias in machine learning](case-a.qmd)
-   Case Study B: [The caveat is the caviar: navigating ethics to protect endangered river wildlife](case-b.qmd)
-   Case Study C: [To reuse or not reuse, that is the key question!](case-c.qmd)
-   Case Study D: [Navigating the complexities of ownership zones](case-d.qmd)
