---
title: "EDS 213: Databases and Data Management"
---

## Course description

The goals of the course were to give MEDS students the skills they need to practically, successfully, and ethically manage their data, and to create, manage, and use relational databases where appropriate. Relational database topics went farther than just SQL queries and included a significant unit on data modeling and database constraints and integrity, in addition to advanced database topics such as indexes and accessing databases from programming environments. The data management portion includes analyzing data from an ethical perspective, creating standards-compliant metadata, and employing data de-identification techniques. The course also included a unit on the Unix command line, with an emphasis on creating reusable Bash scripts, given in the spirit that Bash is a generally useful tool that all data scientists should have at least some familiarity with.


## Data

For the database portion of the course, the [Arctic Shorebird Demographics Network](https://doi.org/10.18739/A2222R68W) dataset, obtained from the [Arctic Data Center](https://arcticdata.io), was used as a running example. While this dataset is not distributed as a relational database (it is packaged as a set of related CSV files), its structure is highly amenable to a relational approach and provides a realistic example of where and why one would want to use a relational database in the Earth and environmental sciences. It also provides just enough complexity to support realistic and complex queries and views. Note that the dataset used in the course, and included in this archive, is a cleaned-up subset of the full dataset. It is necessarily a subset of the full dataset to keep the size and complexity manageable for pedagogical purposes, and it had to be cleaned up because, unfortunately, the full dataset has many errors that would have precluded creating foreign keys.

A class data GitHub repository, linked below, is used to distribute data files to students. Each week a new directory of files will be added to the repository and the students will be asked to pull the repository to their local environment to get the updates. 


## Database

[DuckDB](https://duckdb.org/) is used as the database platform due to its analytical focu, growing set of extensions such as spatial analysis,  and its strict implementation of data types. 


## Instructors

- Julien Brun (jb160\@ucsb.edu)
- Greg Janée (gjanee\@ucsb.edu)
- Annie Adams (aradams\@ucsb.edu)
- Renata Curty (rcurty\@ucsb.edu)

Best way to contact us: email or course slack channel for general questions


## Schedule

- Class: Monday & Wednesday 9:30-10:45 AM (BH 1424)
- Lab: Wednesday 1 - 2:20 pm
- Office hours: 
  - Julien & Greg: Wed after class in Oak room 
  - Annie: Thursday 11 am - 12 pm in BH 3418


## Course content

[Syllabus](https://docs.google.com/document/d/1wjTt38KQZHUeTCkD-R_6fbhwqVYazCeFY0X_4ISwP98/)

[Installing DuckDB](installing-duckdb.qmd)

[Resources](resources.qmd)

[Class data GitHub repository](https://github.com/UCSB-Library-Research-Data-Services/bren-eds213-data)


## Modules

| Week | Lecture                                                                |   Lab   |
|------|------------------------------------------------------------------------|------------------------------------|
| 1    | [Relational databases and data modeling](modules/week01/index-01.qmd)  | Finding your relational dataset |
| 2    | [Analyzing & cleaning the bird dataset (from csv)](modules/week02/index-02.qmd) | Design the schema of your database |
| 3    | [Introduction to SQL (part 1) & DuckDB](modules/week03/index-03.qmd)            | Clean and ingest |
| 4    | [SQL part 2 + Analyzing the bird database using SQL](modules/week04/index-04.qmd)| Data exploration and analysis using SQL |
| 5    | [I/O & data management + DuckDB and Parquet files](modules/week05/index-05.qmd) | Visualize your data |
| 6    | [Using R & Python to query databases + bash programming](modules/week06/index-06.qmd)  | Finalize and document |
| 7    | [Capturing your computing environment + Documenting your work: metadata](modules/week07/index-07.qmd) | Database showcases |
| 8    | [Databases advanced topics + Ethical & responsible data mgnt](modules/week08/index-08.qmd)  |  -  |
| 9    | [Sensitive data](modules/week09/index-09.qmd)                          | Sensitive data lab |
| 10   | [Data licensing and publication](modules/week10/index-10.qmd)          |  -  |

