---
title: "Week 7 - Metadata for the clean snow cover dataset"
---

<<<<<<< HEAD
Use your week 2 assignment when you cleaned the snow cover dataset or this version [here]()

Total points: 50

Instructions:

- Follow the instructions below to write the metadata for the cleaned version of the snow cover table (the one you write at the end of your cleaning script) and add this information to the README.md of your repository used for week2 (or start a new one if you prefer)
- You can reuse some of the original metadata
- Be sure to adapt the metadata for the columns you modified during your data cleaning
- Ensure that you describe how missing data was handled 


```
DATA & FILE OVERVIEW

1. File List: <list all files (or folders, as appropriate for dataset organization) contained in the dataset, with a brief description of their content>

2. Relationship between files, if important:

3. Additional related data collected that was not included in the current data package:

4. Are there multiple versions of the dataset? 


DATA-SPECIFIC INFORMATION FOR:

[FILENAME] <repeat this section for each dataset, folder or file, as appropriate>

1. Number of variables:

2. Number of cases/rows:

3. Variable List: <list variable name(s), description(s), unit(s)and value labels as appropriate for each>

4. Missing data codes: <list code/symbol and definition>

5. Specialized formats or other abbreviations used:

SHARING/ACCESS INFORMATION

1. Licenses/restrictions placed on the data:

2. Links to publications that cite or use the data:

3. Links to other publicly accessible locations of the data:

4. Links/relationships to ancillary data sets: <any supplementary data sources that support analysis or classification of the datasets, eg., plant taxonomy table.)>

5. Was data derived from another source? If yes, list source(s): <list citations to original sources>

6. Recommended citation for the project:
```
=======
Total Points: 50

Instructions:

Each capstone project group must submit a README file in Markdown (.md) format that thoroughly documents the datasets used or produced in the project. You can customize this [README Template](https://zenodo.org/records/10828379) as needed to fit the specifics of your project.
For datasets with shared characteristics (e.g., similar file formats, variables, or units such as images or time series data), you may streamline the documentation by describing shared features once. 
If your group, your client, or the original data source adopted a metadata standard, you must acknowledge this in the README and briefly describe the standard used.
>>>>>>> f1a9e7fc2b00739c3b8d493fb670ad4260dcfeeb

Submission details are available on Canvas.
