---
title: "Week 7 - Computing environments  &  Metadata standards"
---


## Virtual Computing Environments

### Slides and other materials

[slides-virtual-environments.pptx](slides-renv-07.pptx)

[Class Renv Exercise](virtual-environments-notes.md)


## Metadata standards

### Learning goals

- Understand the role of metadata standards in facilitating the management, discovery, interoperability, and reuse of digital resources and research data.
- Recognize the importance of adhering to domain-specific metadata standards and determining which standard should be used.
- Identify metadata standards commonly used in Earth and Environmental Sciences research.


### Slides

[slides-07.pptx](slides-07.pptx)

### Homework
[homework-week07-metadata](hw-07-1.qmd)

### Related resources:

-   [Research Data Alliance (RDA) Metadata Standard Catalog](https://rdamsc.bath.ac.uk)
-   [DataOne Repository](https://www.dataone.org)

### Recommended readings

1.  Gries, C., Hanson, P. C., O'Brien, M., Servilla, M., Vanderbilt, K., & Waide, R. (2023). The Environmental Data Initiative: Connecting the past to the future through data reuse. Ecology and Evolution, 13(1), e9592. <https://doi.org/10.1002/ece3.9592>

2.  Leipzig, J., Nüst, D., Hoyt, C. T., Ram, K., & Greenberg, J. (2021). The role of metadata in reproducible computational research. Patterns, 2(9), <https://doi.org/10.1016/j.patter.2021.100322>


<hr>

### Recommended readings

1.  Marwick B, Boettiger C, Mullen L. 2018. Packaging data analytical work reproducibly using R (and friends). PeerJ Preprints 6:e3192v2 <https://doi.org/10.7287/peerj.preprints.3192v2>.

2.  Powers, S. M., & Hampton, S. E. (2019). Open science, reproducibility, and transparency in ecology. Ecological applications : a publication of the Ecological Society of America, 29(1), e01822. <https://doi.org/10.1002/eap.1822>.

3.  PyPA Guides. (Apr. 4, 2023). Installing packages using pip and virtual environments. <https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment>.

4.  Ushey, K. (April, 6, 2023). Renv: Project environments (Version 0.17.3) \[Computer software\]. Retrieved from <https://cran.r-project.org/web/packages/renv/renv.pdf>.



